print("1.I\'m \"ok\"!")
print("2.I\'m learning \n \"python\"!")
print("3.\\\t\\")
print(r'4.\\\t\\.')
print('''line1...line2...line3''') 
print("n = 123")
print("f = 456.789")
print("s1 = 'Hello,World'")
print("s2 = r''Hello,\\'Adam\\'''")
print("s3 = r\'Hello,\"Bart\"\'")
print("s4 = r'''Hello,\nLisa!'''")